# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: prepare environment
        run: valgrind --tool=memcheck --leak-check=yes ./Tests/Tests
  build:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - run: make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: main.out
  test:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: make test